# typed: strict
# frozen_string_literal: true

# This file is auto-generated by scripts/update-homebrew-formula.sh on release.
class Screpdb < Formula
  desc "Advanced StarCraft: Brood War replay reporting tool (CLI + local dashboard)"
  homepage "https://github.com/marianogappa/screpdb"
  version "1.27.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.27.0/screpdb-darwin-arm64"
      sha256 "69318ce443bd5be934b96c64bd4598e3fca9095005504f6de03ddfcff81ec8cf"
    end
    on_intel do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.27.0/screpdb-darwin-amd64"
      sha256 "045dfd495fe8f331b9ddf93e950a9ea39ab9a5c2956a8f7213603eb8374fbead"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.27.0/screpdb-linux-arm64"
      sha256 "d73eff0f49f8fb0d1fc36f66bd77f7b85c6c126757b8c7df9782784d9a5f85c2"
    end
    on_intel do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.27.0/screpdb-linux-amd64"
      sha256 "afa0bbd06eb4a04acacb01b0fb430a75f3b6b517976c19dc579969001b63dde0"
    end
  end

  def install
    bin.install Dir["screpdb-*"].first => "screpdb"
  end

  def caveats
    dir = OS.mac? ? "~/Library/Application Support/screpdb" : "${XDG_CONFIG_HOME:-$HOME/.config}/screpdb"
    <<~EOS
      screpdb keeps its database and settings in a single folder:
        #{dir}
      This is left untouched on uninstall. To remove your data too, run:
        rm -rf "#{dir}"
    EOS
  end

  test do
    assert_match "screpdb", shell_output("#{bin}/screpdb --help 2>&1")
  end
end
