# typed: strict
# frozen_string_literal: true

# This file is auto-generated by scripts/update-homebrew-formula.sh on release.
class Screpdb < Formula
  desc "Advanced StarCraft: Brood War replay reporting tool (CLI + local dashboard)"
  homepage "https://github.com/marianogappa/screpdb"
  version "1.23.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.23.2/screpdb-darwin-arm64"
      sha256 "60b9b622f252fa25793ebbcffb7cc10d3b45124f168989c88e4e70eceee49115"
    end
    on_intel do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.23.2/screpdb-darwin-amd64"
      sha256 "1d02fdf0d5bc1c72ee7817216a389264713661e4cfafeb76076ed4ced2676292"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.23.2/screpdb-linux-arm64"
      sha256 "50b59508780e96042533d3138449a178f0bc0e1ad7724022c6914ce36249a079"
    end
    on_intel do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.23.2/screpdb-linux-amd64"
      sha256 "6400981fb6b7ee9568f7760366c520baf2dbc07874cd024bfaadebae391d9129"
    end
  end

  def install
    bin.install Dir["screpdb-*"].first => "screpdb"
  end

  test do
    assert_match "screpdb", shell_output("#{bin}/screpdb --help 2>&1")
  end
end
