# typed: strict
# frozen_string_literal: true

# This file is auto-generated by scripts/update-homebrew-formula.sh on release.
class Screpdb < Formula
  desc "Advanced StarCraft: Brood War replay reporting tool (CLI + local dashboard)"
  homepage "https://github.com/marianogappa/screpdb"
  version "1.24.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.24.1/screpdb-darwin-arm64"
      sha256 "28fda8718552254ef3a0900bf4b16e6227dc79e046267771051cf9c398a6eafd"
    end
    on_intel do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.24.1/screpdb-darwin-amd64"
      sha256 "62760c3ec96bc36091fb38d72c6627970800bb89d0dd631019f512a2cb4bd18c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.24.1/screpdb-linux-arm64"
      sha256 "d7773381150517a0a20b912fd781ab704410c25cabce4e97c6d976b7e7baa50a"
    end
    on_intel do
      url "https://github.com/marianogappa/screpdb/releases/download/v1.24.1/screpdb-linux-amd64"
      sha256 "a38c2f794fd2886a8fbfb498012a39aacc367f3d10197f3ce8bac7862cd3cf41"
    end
  end

  def install
    bin.install Dir["screpdb-*"].first => "screpdb"
  end

  def caveats
    dir = OS.mac? ? "~/Library/Application Support/screpdb" : "${XDG_CONFIG_HOME:-$HOME/.config}/screpdb"
    <<~EOS
      screpdb keeps its database and settings in a single folder:
        #{dir}
      This is left untouched on uninstall. To remove your data too, run:
        rm -rf "#{dir}"
    EOS
  end

  test do
    assert_match "screpdb", shell_output("#{bin}/screpdb --help 2>&1")
  end
end
